version : "3.7"

services:
  server:
        build: ./php
        ports:
          - "80:80"
        container_name: 'personal-cloud-php'
        links: 
          - database
        volumes:
          - type: bind
            source: /home/blupie/projects/personal-cloud/personal-cloud/server
            target: /var/www/html
        restart: 'no'
        
  database:
        build: ./mysql
        command: mysqld --default-authentication-plugin=mysql_native_password 
        container_name: 'personal-cloud-mysql'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: backend_db
            MYSQL_USER: user
            MYSQL_PASSWORD: user
        ports:
            - "3306:3306"
        volumes:
          - .mysql:/var/lib/mysql
          - ./mysql/dbinit:/docker-entrypoint-initdb.d
        restart: 'no'

  adminer:
      build: ./adminer
      container_name: 'personal-cloud-adminer'
      links:
        - database
      restart: 'no'
      ports:
        - "8080:8080"